# Generated by Django 3.2 on 2021-09-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=120)),
                ('date_published', models.DateField()),
                ('isbn_number', models.CharField(max_length=120)),
                ('number_of_pages', models.PositiveIntegerField()),
                ('link_to_cover', models.URLField()),
                ('language', models.CharField(max_length=120)),
            ],
        ),
    ]
